wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1659710970
    t:
      1:
      - 3
      - 53
      - 55
      3:
      - 19
      - 35
      4: 3.7.4
      5: 0.12.21
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 256
